-- Generated by Profession Leveler
ProfessionLevelerScan_TargetProfessionId = 185
WowAhPlannerScan_TargetProfessionId = ProfessionLevelerScan_TargetProfessionId
ProfessionLevelerScan_RecipeTargets = {
  { recipeId = "spice-bread", minSkill = 1, grayAt = 55, reagents = { 2678, 30817 } },
}
WowAhPlannerScan_RecipeTargets = ProfessionLevelerScan_RecipeTargets
